export enum ActionType {
    GET_NAVIGATION_LIST = '[NAVIGATION] GET_NAVIGATION_LIST',
    GET_NAVIGATION_LIST_SUCCESS = '[NAVIGATION] GET_NAVIGATION_LIST_SUCCESS',
    GET_NAVIGATION_LIST_FAILURE = '[NAVIGATION] GET_NAVIGATION_LIST_FAILURE',
}
export class NavigationPanelAction {
    constructor(type: ActionType){}
}