export enum NotificationActionType {
    GET_NOTIFICATIONS_LIST = '[NOTIFICATION] GET_NOTIFICATIONS_LIST',
    GET_NOTIFICATIONS_LIST_SUCCESS = '[NOTIFICATION] GET_NOTIFICATIONS_LIST_SUCCESS',
    GET_NOTIFICATIONS_LIST_FAILURE = '[NOTIFICATION] GET_NOTIFICATIONS_LIST_FAILURE',
    UPDATE_NOTIFICATION = '[NOTIFICATION] UPDATE_NOTIFICATION',
    DELETE_NOTIFICATION = '[NOTIFICATION] DELETE NOTIFICATION',
    DELETE_NOTIFICATIONS = '[NOTIFICATION] DELETE_NOTIFICATIONS'
}
export class NotificationAction {
    constructor(type: NotificationActionType){}
}