export enum NotificationActionType {
    GET_NOTIFICATIONS_LIST = '[NOTIFICATION] GET_NOTIFICATIONS_LIST',
    GET_NOTIFICATIONS_LIST_SUCCESS = '[NOTIFICATION] GET_NOTIFICATIONS_LIST_SUCCESS',
    GET_NOTIFICATIONS_LIST_FAILURE = '[NOTIFICATION] GET_NOTIFICATIONS_LIST_FAILURE',

    ADD_NOTIFICATION = '[NOTIFICATION] UPDATE_NOTIFICATION',
    UPDATE_NOTIFICATION_ITEM = '[NOTIFICATION] UPDATE_NOTIFICATION_ITEM',
    UPDATE_IS_NEW_NOTIFICATION = '[NOTIFICATION] UPDATE_IS_NEW_NOTIFICATION',
    UPDATE_NOTIFICATION_ITEM_IS_ACTIVE = '[NOTIFICATION] UPDATE_NOTIFICATION_ITEM_IS_ACTIVE',
    DELETE_NOTIFICATION = '[NOTIFICATION] DELETE_NOTIFICATION',
    DELETE_NOTIFICATIONS = '[NOTIFICATION] DELETE_NOTIFICATIONS',
    HIDE_NOTIFICATIONS = '[NOTIFICATION] HIDE_NOTIFICATIONS'
}
export class NotificationAction {
    constructor(type: NotificationActionType){}
}