export enum UserInfoActionType {
    GET_USER_INFO_DATA = '[USER_INFO] GET_USER_INFO_DATA',
    GET_USER_INFO_DATA_SUCCESS = '[USER_INFO] GET_USER_INFO_DATA_SUCCESS',
    GET_USER_INFO_DATA_FAILURE = '[USER_INFO] GET_USER_INFO_DATA_FAILURE'
}